angular:
  - init
  - home
person:
  age: 10
  name: aa
  num:
    - 1
    - 2
server:
  port: 8080
#默认启动环境
spring:
  profiles:
    active: dev
---
server:
  port: 8081
spring:
  profiles: dev
---
server:
  port: 8082
spring:
  profiles: prod