person:
    age: 10
    name: aa
    num:
      - 1
      - 2
server:
  port: 8080
spring:
 profiles: dev
---
server:
  port: 8081
spring:
 profiles: dev
---
server:
  port: 8082
spring:
 profiles: prod