#默认使用HikariCP 效率较高
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.99.73.15:3306/jdbc
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource