spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.99.73.15:3306/games?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    #控制台显示sql
    show-sql: true
    #跟新或者创建表结构
    hibernate:
      ddl-auto: update