spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.99.73.15:3306/games?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

#mybatis 驼峰和下划线的转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml