spring:
  rabbitmq:
    host: 47.99.73.15
    port: 5672
    username: guest
    password: guest
    #手动ack
    listener:
      simple:
        acknowledge-mode: manual
    #消息确认
    publisher-confirms: true